setup configuration
setup: aConfiguration view: aRTView target: aPitekun
	self 
		setupBasic: aConfiguration view: aRTView target: aPitekun;
		setupMicroprint: aConfiguration view: aRTView target: aPitekun;
		setupFullSource: aConfiguration view: aRTView target: aPitekun;
		setupFullOrMicro: aConfiguration view: aRTView target: aPitekun;
		setupMethodGroup: aConfiguration view: aRTView target: aPitekun;
		setupEdges: aConfiguration view: aRTView target: aPitekun;
		setupCobwebItems: aConfiguration view: aRTView target: aPitekun;
		setupPitekun: aPitekun